# My variables
name: yogesh kumar
description: notes 
google_verification: null
baseurl: /notes

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
# pygments: true
highlighter: rouge
markdown: kramdown
# kramdown:
#   input: GFM
#   hard_wrap: false
#   auto_ids: true
  # syntax_highlighter: rouge
